model:
  name: "convnext"
  backbone:
    name: "convnext_base"
    pretrained: true
    in_chans: 1
    img_size: 224
    drop_rate: 0.2
    drop_path_rate: 0.3
    
  classification_head:
    hidden_size: 768
    dropout_rate: 0.3
    num_classes: 14
    
  segmentation_head:
    decoder_channels: [768, 384, 192, 96, 48]
    activation: "gelu"
    attention_type: "cbam"
    use_batchnorm: true

training:
  optimizer:
    name: "adamw"
    learning_rate: 2e-4
    weight_decay: 0.05
    
  scheduler:
    name: "one_cycle"
    max_lr: 2e-4
    pct_start: 0.3
    
  augmentation:
    resize_scale: [0.75, 1.0]
    resize_ratio: [0.85, 1.15]
    rotate_limit: 25
    brightness_contrast_prob: 0.35
    noise_prob: 0.35
    
  batch_size: 12
  num_epochs: 75
  mixed_precision: true
  gradient_clip_val: 1.0