model:
  name: "swin_base"
  backbone:
    name: "swin_base_patch4_window7_224"
    pretrained: true
    in_chans: 1
    img_size: 224
    window_size: 7
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.2
    
  classification_head:
    hidden_size: 512
    dropout_rate: 0.3
    num_classes: 14
    
  segmentation_head:
    decoder_channels: [512, 256, 128, 64, 32]
    activation: "relu"
    attention_type: "scse"
    use_batchnorm: true

training:
  optimizer:
    name: "adamw"
    learning_rate: 1e-4
    weight_decay: 0.01
    
  scheduler:
    name: "reduce_on_plateau"
    mode: "min"
    factor: 0.5
    patience: 5
    min_lr: 1e-6
    
  augmentation:
    resize_scale: [0.8, 1.0]
    resize_ratio: [0.9, 1.1]
    rotate_limit: 15
    brightness_contrast_prob: 0.3
    noise_prob: 0.3
    
  batch_size: 8
  num_epochs: 50
  mixed_precision: true
  gradient_clip_val: 1.0